### ISSUE TITLE
这个怎么添加到/lichess-bot

### ISSUE THREAD

**Issue by fakerJZH** [S-Lucien/chess-engine#1]

**Comment by S-Lucien** [comment]
把python程序打包成exe放到lichess的engines目录下，配一下config.yml。参考https://github.com/lichess-bot-devs/lichess-bot?tab=readme-ov-file

**Comment by fakerJZH** [comment]
/lichess-bot/lib/lichess.py", line 15, in <module>
    JSON_REPLY_TYPE = dict[str, Any]
TypeError: 'type' object is not subscriptable    运行后报这个呢

**Comment by fakerJZH** [comment]
<img width="281" alt="image" src="https://github.com/S-Lucien/chess-engine/assets/73507847/a8b1d84e-54ef-463a-9833-ad8dc0d87142">

**Comment by S-Lucien** [comment]
哪个步骤出的问题？我这边目前还能正常运行

**Comment by fakerJZH** [comment]
我有一个UI，能不能帮我把算法加入进去，有偿

**Comment by S-Lucien** [comment]
这是两年前写的了，我现在也不怎么搞python。有需要你自己看看吧，或者找找别的。
